version: '3.3'

services:
  app:
    image: rockdog/sinatra:latest
    ports:
      - 4567:4567
    networks:
      - traefik-public
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
      labels:
        - traefik.frontend.rule=Host:luvhub.de
        - traefik.enable=true
        - traefik.port=4567
        - traefik.tags=traefik-public
        - traefik.docker.network=traefik-public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https

networks:
  traefik-public:
    external: true
